SERIAL_PORT = 'COM5'
BAUDRATE = 9600
MOTOR_VELOCITY = 9  #mm/s
LATENCY = 0.1   #Latencia real está em aproximadamente 0,05s
PICKER_TIME_INTERVAL = 4.5

CAM_PORT = 1
IMAGES_PATH = "C:\\Users\\rodri\\Projects\\TCC\\python\\data\\"

IMAGE_PIXEL_WIDTH = 640
IMAGE_PIXEL_HEIGHT = 480
IMAGE_MM_WIDTH = 120

REALITY_PROPORTION = IMAGE_PIXEL_WIDTH / IMAGE_MM_WIDTH     

DELAY_SETUP = 48
DELAY_GETTING = 5
INTERVAL = 1

ROBOFLOW_API_KEY = "kVbgjD1FriaPGLkieeec"
ROBOFLOW_PROJECT_NAME = "strawberry---ripe---not-ripe"
ROBOFLOW_PROJECT_VERSION = 3
ROBOFLOW_CONFIDENCE_LEVEL = 3
ROBOFLOW_OVERLAP_LEVEL = 20